language: node_js
node_js: stable
install:
- npm install
script:
- npm run init:app
- npm run test
- npm run build
after_success:
- ./ci/update-gh-pages.sh > /dev/null 2>&1
env:
  global:
    secure: Oac6lChOYgBY6lo/EF6s7zgOgGEx0eg9fOaoQhJYG0zFJS9I9VRnoxPhP9x67HzOXI/erZUar2t7/99SCjcDrNjgwONhdCK1ACSiy3Rxawq/Pl7CQsZyVyfQpcvJsUw3/uddwp+UZCksD/EalKG2XubIOfPSB/mN/q0C6LAjgkpSNCndfdeQoVz5J7fGxX3R7t3oGEHmHSm2yw6kKxCffaiJj1gvFVLAm2IUzCujbFSjs2Bdr4SW9Z3/HwJ6UElW/0xJt4JAz9dN1CVREedg/IXy5jO/1qvmNPeF3qjy6u1vraxNsogKA5HwHmcvX8A3IF7zOh1eDHBG88bKW1APi/90xtsN27Nfb2sKUglDDcnoPdBuWsXTOqpkiBJHuMabrF/xnSOmyveheQxcPJzjB8P3x2rMPvoh38sdiNL7Tr0yw/yO0yvFfOwGny60KyM2zzMnMsuzkT+C9F11ZUWA6VJISdoGcafRq16RMgokluR94Gi6gsbWd16f8eIdWVJZ76VfODCjXC3OBMzTA1WUMoIgSMEyT8LWCWDh7rlpI0NnBcP4V1e/9k6ADZaI9RRwn6zP3RPJ4g8blCCGGfau6gYB+dfQUdsjGrQvEbuJZKit7xpFigmWf4Fy44E82H9UA8HiMimndss936kxklXmAtWpMO4QKQ4Z81+PYTrtWZU=
